require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb
    - vendor/**/*
    - bin/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - db/**/*

# This is too aggressive with our use of Seattle.rb style lack of parens on method calls
# E.g., return redirect_to [:photos]
# Rubocop thinks that `redirect_to` is a collection and `:photos` is a hash key
Layout/SpaceBeforeBrackets:
  Enabled: false

Metrics/AbcSize:
  Max: 74

Metrics/BlockLength:
  Max: 99
  Exclude:
    - config/routes.rb

Metrics/ClassLength:
  Max: 135

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/MethodLength:
  Max: 31
  Exclude:
    - db/migrate/*

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 15

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/RedundantFetchBlock:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# For now we disable this, since explicit hash value sounds better to use
Style/HashSyntax:
  Enabled: false

# For now we disable this, since I prefer explicit block name
Naming/BlockForwarding:
  Enabled: false
